### ISSUE TITLE
Menu Scale Incorrect for a few Games

### ISSUE THREAD

**Issue by Smoker1** [Finalcheat/finalcheat.github.com#1]
Wondering how to fix this. 
![2018-07-10-213103](https://user-images.githubusercontent.com/8584462/42599516-5264d52c-8514-11e8-9175-52005bac0e38.jpg)
![2018-07-10-213210](https://user-images.githubusercontent.com/8584462/42599517-52824f30-8514-11e8-9375-0fb93f1d6b6c.jpg)

**Comment by Finalcheat** [comment]
next version will fix this.
I have been busy with work recently and have no time to update.
